In [1]:
import pandas as pd

df_clean = pd.read_csv("cleandataset.csv")
df_clean

,Unnamed: 0.1,Unnamed: 0,reviewId,content,score,thumbsUpCount,appVersion,bank,Date
0,0,0,bfb0b4a9-6b7d-41c7-9fe0-54c8eacc20bc,improve the app compare to other bank it was e...,1,0,1.30.1,Metrobank,2026-09-08
1,1,1,59c2b22c-693a-4599-b39c-02afad058f71,"always ""something went wrong"" in transactions",1,0,1.30.1,Metrobank,2026-09-08
2,2,2,06881c1e-0160-42d5-a441-13f40a689e8a,"Several restart, uninstall and reinstalling th...",1,0,1.30.1,Metrobank,2026-09-08
3,3,3,8549e4d0-5ead-4c40-8d6d-5a16b5d6e3c5,Xiaomi white screen issue till now,1,0,1.30.1,Metrobank,2026-09-08
4,4,4,92478c30-4ebd-4c14-b2a1-1b4faa322743,NOT RESPOND AT ALL!!!!! after you update and a...,1,0,1.30.1,Metrobank,2026-09-08
...,...,...,...,...,...,...,...,...,...
11995,11995,11995,a7b49f52-01bb-43cc-924b-5a87b2a25356,good,5,0,2.58.4,UnionBank,2025-11-24
11996,11996,11996,7be96faf-97b0-42f4-ad9a-52577662096a,Very cumbersome interface. hard to use,2,1,2.59.2,UnionBank,2025-11-24
11997,11997,11997,5b38a5d4-2339-4201-b490-024caf66627f,the transaction is very fast including the ins...,5,2,2.59.2,UnionBank,2025-11-24
11998,11998,11998,8e5edc59-b0a4-42ba-ab98-2f410c3f7591,easy and safe to use,5,0,2.59.2,UnionBank,2025-11-24
11999,11999,11999,f0ad3a8e-da46-49e3-9d92-84b3880904e1,so easy and secure,5,0,2.59.2,UnionBank,2025-11-24

In [9]:
df_clean.drop(columns=["replyContent"], inplace=True)

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              12000 non-null  str
 1   userName              12000 non-null  str
 2   userImage             12000 non-null  str
 3   content               12000 non-null  str
 4   score                 12000 non-null  int64
 5   thumbsUpCount         12000 non-null  int64
 6   reviewCreatedVersion  10430 non-null  str
 7   at                    12000 non-null  str
 8   repliedAt             5744 non-null   str
 9   appVersion            10430 non-null  str
 10  bank                  12000 non-null  str
dtypes: int64(2), str(9)
memory usage: 1.0 MB

In [11]:
df_clean.drop(columns=["repliedAt"], inplace=True)

In [18]:
df_clean.isna().sum()

reviewId                   0
userName                   0
userImage                  0
content                    0
score                      0
thumbsUpCount              0
reviewCreatedVersion    1570
at                         0
appVersion              1570
bank                       0
dtype: int64

In [12]:
df_clean["at"] = pd.to_datetime(df_clean["at"])

In [8]:
df_clean['at']

0        2026-09-08 06:38:04
1        2026-09-08 02:33:57
2        2026-09-08 02:33:30
3        2026-09-08 01:13:14
4        2026-09-08 00:12:14
                ...
11995    2025-11-24 17:06:55
11996    2025-11-24 15:07:53
11997    2025-11-24 14:00:06
11998    2025-11-24 13:27:04
11999    2025-11-24 12:50:31
Name: at, Length: 12000, dtype: str

In [53]:
df_clean.info()
print(df_clean["thumbsUpCount"].unique())

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   reviewId       12000 non-null  str
 1   content        12000 non-null  str
 2   score          12000 non-null  int64
 3   thumbsUpCount  12000 non-null  int64
 4   at             12000 non-null  datetime64[us]
 5   appVersion     10430 non-null  str
 6   bank           12000 non-null  str
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 656.4 KB
[  0   1   2   3   7   4   6  14   5  11  12  15  20  17  25   8  22  18
   9  24  26  37  21  23  13  31  32  40  46  84  71  10  19 121  27 233
 105 328  28  30  95  38  54  35 155]

In [ ]:
df_clean.drop(columns=["userName"], inplace=True)

In [ ]:
print(df_clean[df_clean["bank"] != "Metrobank"]["bank"].head(50))

In [45]:
print(df_clean["reviewId"].unique())

<StringArray>
['bfb0b4a9-6b7d-41c7-9fe0-54c8eacc20bc',
 '59c2b22c-693a-4599-b39c-02afad058f71',
 '06881c1e-0160-42d5-a441-13f40a689e8a',
 '8549e4d0-5ead-4c40-8d6d-5a16b5d6e3c5',
 '92478c30-4ebd-4c14-b2a1-1b4faa322743',
 '7adc3030-c97d-46e2-b35c-7f3ae2dc50ed',
 'e273b2ea-00b6-4050-8af4-53dc8da742cf',
 'fe6bafb9-8bda-46ad-8952-b949e750db82',
 'd2bf3d4a-096a-4144-8662-f449c385e496',
 'cc2cd6e3-bae7-4032-bb45-7744254b24bc',
 ...
 'a9026b8d-5f9a-401b-9b37-881217f848a4',
 'f17dc1af-aab3-4308-950a-563b5aea9ffc',
 '8571b1f0-43cb-4982-9e14-4c72eb66563f',
 'dd18ce08-de51-4d8d-9969-f0b50ee7372d',
 '15ac9f8b-af88-4fca-bd1f-c3e95c694c79',
 'a7b49f52-01bb-43cc-924b-5a87b2a25356',
 '7be96faf-97b0-42f4-ad9a-52577662096a',
 '5b38a5d4-2339-4201-b490-024caf66627f',
 '8e5edc59-b0a4-42ba-ab98-2f410c3f7591',
 'f0ad3a8e-da46-49e3-9d92-84b3880904e1']
Length: 12000, dtype: str

In [46]:
print(df_clean.isna().sum())

reviewId                   0
content                    0
score                      0
thumbsUpCount              0
reviewCreatedVersion    1570
at                         0
appVersion              1570
bank                       0
dtype: int64

In [47]:
(df_clean["reviewCreatedVersion"] == df_clean["appVersion"]).value_counts()

True     10430
False     1570
Name: count, dtype: int64

In [50]:
df_clean.drop(columns=["reviewCreatedVersion"], inplace=True)

In [61]:
df_clean[df_clean["score"] > 3].head(20)

,reviewId,content,score,thumbsUpCount,at,appVersion,bank
13,652b5cf1-0ee1-45e1-bb33-8b6d2dd93cea,so good 👍,5,0,2026-09-07 12:13:57,1.30.1,Metrobank
16,3bb0d8e3-fa82-442e-9342-7b16fbc81c7e,update my old Metro bank account I forgot my p...,5,0,2026-09-06 23:30:20,1.29.0,Metrobank
29,391411e0-6031-4422-bf96-6805502224b3,fast and responsive,5,0,2026-09-05 19:50:31,1.30.1,Metrobank
32,c94575dd-bf3a-4082-b58b-c0d34165956f,disgusting app.. up to now it's not working..,5,0,2026-09-05 17:09:43,NaN,Metrobank
42,1ed7bdd7-72ff-4b4e-8802-07722c9faf89,very trusted,5,0,2026-09-05 02:01:42,NaN,Metrobank
66,b57c1287-e676-4d88-b97c-e36f5e949f94,how to put my passcode,5,0,2026-09-03 06:19:59,1.30.1,Metrobank
68,16b7056d-7a5d-4efa-a3ea-c20ec6e4fb80,"Dear Developer, I hope you add an option to hi...",4,0,2026-09-02 21:48:02,1.30.1,Metrobank
70,8835c4ff-c889-4093-a42d-1f2d69f09a36,very slow sometimes .,5,0,2026-09-02 18:51:41,1.30.1,Metrobank
78,98c6c619-2fa8-40ea-b77f-6071f24dba98,ok,5,0,2026-09-02 08:54:31,1.30.1,Metrobank
82,1601c66e-5cc0-44e3-bccb-403a3ecedf4e,is to hard for me to open my metro bank apps I...,4,0,2026-09-01 21:49:05,1.30.1,Metrobank
105,87e16ee4-734b-431c-8608-5490a9eebfdd,"Good app but keeps on reporting ""Unsafe Connec...",4,0,2026-09-01 03:14:50,1.30.1,Metrobank
106,76abc0d9-5417-4e4b-b6f9-e060bbdc771d,nice,5,0,2026-09-01 00:15:05,1.30.1,Metrobank
115,70996c72-c737-49e7-9207-c72d668054cb,good,5,0,2026-08-31 12:55:43,1.30.1,Metrobank
134,c1167a25-a146-472e-ada5-971bd1fb84ea,mabilis at madali mg transfer Ng Pera kahit sa...,5,0,2026-08-30 06:42:53,1.30.1,Metrobank
150,15d09fee-8aa9-4be5-bf8f-5ebd2dc926e9,I am so very satisfied in this bank excellent,5,1,2026-08-29 09:17:26,NaN,Metrobank
160,b98b3ac7-1fd4-4a01-a9d8-38ae6791430c,Why I can't log in?,5,0,2026-08-28 22:09:51,1.26.0,Metrobank
196,d10b629c-2551-432b-919a-d4a48b63de46,laging maaasahan,5,0,2026-08-27 19:37:19,1.30.1,Metrobank
295,e9a5ded2-fc15-4d84-adc9-a994a7ca5ebd,so far so good,5,0,2026-08-22 07:37:35,1.30.1,Metrobank
298,40c9370e-27e8-4c37-acf9-d633bd59df03,This app often experience system maintenance t...,5,2,2026-08-21 21:21:27,1.30.1,Metrobank
305,b9e7eaa5-4223-488c-a351-f58d13214969,why this app is close for me,5,0,2026-08-21 12:12:01,1.30.1,Metrobank

In [10]:
df_clean.to_csv("cleandataset.csv", index=True)

In [66]:
df_clean["Date"] = df_clean["at"].dt.date
df_clean["Time"] = df_clean["at"].dt.time

In [6]:
df_clean

,Unnamed: 0,reviewId,content,score,thumbsUpCount,appVersion,bank,Date
0,0,bfb0b4a9-6b7d-41c7-9fe0-54c8eacc20bc,improve the app compare to other bank it was e...,1,0,1.30.1,Metrobank,2026-09-08
1,1,59c2b22c-693a-4599-b39c-02afad058f71,"always ""something went wrong"" in transactions",1,0,1.30.1,Metrobank,2026-09-08
2,2,06881c1e-0160-42d5-a441-13f40a689e8a,"Several restart, uninstall and reinstalling th...",1,0,1.30.1,Metrobank,2026-09-08
3,3,8549e4d0-5ead-4c40-8d6d-5a16b5d6e3c5,Xiaomi white screen issue till now,1,0,1.30.1,Metrobank,2026-09-08
4,4,92478c30-4ebd-4c14-b2a1-1b4faa322743,NOT RESPOND AT ALL!!!!! after you update and a...,1,0,1.30.1,Metrobank,2026-09-08
...,...,...,...,...,...,...,...,...
11995,11995,a7b49f52-01bb-43cc-924b-5a87b2a25356,good,5,0,2.58.4,UnionBank,2025-11-24
11996,11996,7be96faf-97b0-42f4-ad9a-52577662096a,Very cumbersome interface. hard to use,2,1,2.59.2,UnionBank,2025-11-24
11997,11997,5b38a5d4-2339-4201-b490-024caf66627f,the transaction is very fast including the ins...,5,2,2.59.2,UnionBank,2025-11-24
11998,11998,8e5edc59-b0a4-42ba-ab98-2f410c3f7591,easy and safe to use,5,0,2.59.2,UnionBank,2025-11-24
11999,11999,f0ad3a8e-da46-49e3-9d92-84b3880904e1,so easy and secure,5,0,2.59.2,UnionBank,2025-11-24

In [85]:
df_clean.fillna({'appVersion' : 'unknown'}, inplace=True)

,reviewId,content,score,thumbsUpCount,appVersion,bank,Date
0,bfb0b4a9-6b7d-41c7-9fe0-54c8eacc20bc,improve the app compare to other bank it was e...,1,0,1.30.1,Metrobank,2026-09-08
1,59c2b22c-693a-4599-b39c-02afad058f71,"always ""something went wrong"" in transactions",1,0,1.30.1,Metrobank,2026-09-08
2,06881c1e-0160-42d5-a441-13f40a689e8a,"Several restart, uninstall and reinstalling th...",1,0,1.30.1,Metrobank,2026-09-08
3,8549e4d0-5ead-4c40-8d6d-5a16b5d6e3c5,Xiaomi white screen issue till now,1,0,1.30.1,Metrobank,2026-09-08
4,92478c30-4ebd-4c14-b2a1-1b4faa322743,NOT RESPOND AT ALL!!!!! after you update and a...,1,0,1.30.1,Metrobank,2026-09-08
...,...,...,...,...,...,...,...
11995,a7b49f52-01bb-43cc-924b-5a87b2a25356,good,5,0,2.58.4,UnionBank,2025-11-24
11996,7be96faf-97b0-42f4-ad9a-52577662096a,Very cumbersome interface. hard to use,2,1,2.59.2,UnionBank,2025-11-24
11997,5b38a5d4-2339-4201-b490-024caf66627f,the transaction is very fast including the ins...,5,2,2.59.2,UnionBank,2025-11-24
11998,8e5edc59-b0a4-42ba-ab98-2f410c3f7591,easy and safe to use,5,0,2.59.2,UnionBank,2025-11-24
11999,f0ad3a8e-da46-49e3-9d92-84b3880904e1,so easy and secure,5,0,2.59.2,UnionBank,2025-11-24

In [ ]:
print(df_clean[df_clean['bank'] == "Metrobank"]['content'].head(50))

In [34]:
pd.set_option('display.max_colwidth', None)

In [8]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     12000 non-null  int64
 1   reviewId       12000 non-null  str
 2   content        12000 non-null  str
 3   score          12000 non-null  int64
 4   thumbsUpCount  12000 non-null  int64
 5   appVersion     12000 non-null  str
 6   bank           12000 non-null  str
 7   Date           12000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(4)
memory usage: 750.1 KB

In [7]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'])

In [9]:
df_clean['Date']

0       2026-09-08
1       2026-09-08
2       2026-09-08
3       2026-09-08
4       2026-09-08
           ...
11995   2025-11-24
11996   2025-11-24
11997   2025-11-24
11998   2025-11-24
11999   2025-11-24
Name: Date, Length: 12000, dtype: datetime64[us]

In [4]:
df_clean[df_clean['bank'] == "BPI"][['content', 'score']].head(51)

                                                content  score
6000  I have to transfer money yesterday but i can n...      3
6001                                                wow      5
6002  I don't normally post a review, so me putting ...      1
6003  fix your app. I always encounter errors. App s...      1
6004  I bank transferred last September 5 but until ...      1
6005                      Cant transffer momey to gcash      1
6006  My transfer failed but my money was not return...      1
6007                                    Very convenient      5
6008                               Good very convenient      5
6009  bat kaya ayaw nag open app ko nag clear cache,...      2
6010                                          very nice      5
6011                                             nice 🙂      5
6012  Very easy to use. user since 2013. Thank U BPI...      5
6013                                   my main bank acc      5
6014                                              great      5
6015                                       easy to use👍      5
6016                                        Excellence.      5
6017                    I think my acct has been hacked      1
6018              like bpi because faster transaction..      5
6019                                easy transaction ☺️      4
6020                                      walang kwenta      1
6021                  easy, reliable, on time, and safe      5
6022            the. best than BDO..I feel safe here🇵🇭🫡      4
6023  cannot open this app - wonder if the.phone is ...      3
6024  very good and secured never had a problem usin...      4
6025                                           nice one      3
6026  Nice & convenient to use for paying the bills....      5
6027                I LOVE BPI, THAN YOU AND I HAHAHAHA      5
6028                                        very Nice 😊      5
6029                                               Nice      5
6030                                              happy      5
6031  POTANG INA MO BPI, BAKIT NAWALA FAVORITES OR S...      1
6032  after I deposited money in my bpi account. I c...      1
6033                                             Useful      5
6034                                            great 👍      5
6035                                          very good      5
6036  I have been trying to create a mobile key afte...      3
6037                                      nice and easy      4
6038                                              great      5
6039  worst banking app. always down. sometimes you'...      1
6040                                           nice app      5
6041                                  hirap mong buksan      1
6042  Can't Access my balance and Customer service a...      1
6043  I transfered money to Instapay on my Gcash las...      1
6044  Changing my mobile number is not working, even...      1
6045  nakakadismaya pagdating ko saudi hindi na maop...      1
6046                               It's so very Quality      5
6047  Okay bpi user pro bent and tested for the 10yr...      5
6048                                      give me money      5
6049                                               Good      5
6050                                            Gratzie      5

In [9]:
categories = {
    "Login/Authentication": [
        "login", "log in", "password", "otp", "verification", "locked", "biometrics",
        "sign in", "register",
        "hindi makapasok", "ayaw mag-open", "hindi ma-access", "maka open", "di ma access", "ma-access"
    ],
    "App Stability": [
        "crash", "closes", "freeze", "white screen", "blank screen", "not responding",
        "not working", "maintenance", "bug", "glitch", "broken", "error", "downtime",
        "hindi gumagana", "di gumagana", "sira", "bugok", "puro error"
    ],
    "Performance": [
        "slow", "lag", "loading", "takes forever", "takes a long time",
        "mabagal", "matagal", "pahirap"
    ],
    "Transaction Failures": [
        "something went wrong", "transaction failed", "unable to transfer", "transfer failed",
        "unable to send", "cannot process", "unsuccessful", "cant pay", "instapay",
        "hindi maka send", "hindi ma-transfer", "di ma transfer"
    ],
    "Customer Service": [
        "customer service", "no response", "no reply", "support ticket", "complaint",
        "not assisting", "poor response", "help center",
        "walang sagot", "walang response", "sumagot"
    ],
}

In [7]:
def tag_complaint(text):
    text = text.lower()
    tags = [cat for cat, kws in categories.items() if any(kw in text for kw in kws)]
    return tags if tags else ["Uncategorized"]

In [10]:
test_cases = [
    ("The app keeps crashing every time I open it", ["App Stability"]),
    ("hindi ko ma-access yung account ko", ["Login/Authentication"]),
    ("so slow, matagal mag-load", ["Performance"]),
    ("something went wrong, cannot transfer money", ["Transaction Failures"]),
    ("no response from customer service", ["Customer Service"]),
    ("great app, works perfectly", ["Uncategorized"]), 
]

for text, expected in test_cases:
    result = tag_complaint(text)
    status = "PASS" if result == expected else "FAIL"
    print(f"{status} | text: '{text}' | expected: {expected} | got: {result}")

PASS | text: 'The app keeps crashing every time I open it' | expected: ['App Stability'] | got: ['App Stability']
PASS | text: 'hindi ko ma-access yung account ko' | expected: ['Login/Authentication'] | got: ['Login/Authentication']
PASS | text: 'so slow, matagal mag-load' | expected: ['Performance'] | got: ['Performance']
PASS | text: 'something went wrong, cannot transfer money' | expected: ['Transaction Failures'] | got: ['Transaction Failures']
PASS | text: 'no response from customer service' | expected: ['Customer Service'] | got: ['Customer Service']
PASS | text: 'great app, works perfectly' | expected: ['Uncategorized'] | got: ['Uncategorized']

In [11]:
df_clean['complaint_tags'] = df_clean['content'].apply(tag_complaint)

In [12]:
tag_counts_by_bank = (
    df_clean.explode('complaint_tags')
    .groupby(['bank', 'complaint_tags'])
    .size()
    .unstack(fill_value=0)
)
print(tag_counts_by_bank)

complaint_tags  App Stability  Customer Service  Login/Authentication  \
bank
BDO                       231                32                   372
BPI                       406                44                   260
Metrobank                 682                31                   513
UnionBank                 200               115                   347

complaint_tags  Performance  Transaction Failures  Uncategorized
bank
BDO                      98                    76           2301
BPI                     178                    32           2228
Metrobank               746                   101           1394
UnionBank               109                    20           2326